"""
title: Council Show Details Action
author: chmodxheart
author_url: https://github.com/chmodxheart
funding_url: https://github.com/chmodxheart
version: 0.1.0
description: Interactive button to reveal Council session details and de-anonymization

Council of LLMs - Show Details Action

This action function creates an interactive button that reveals detailed
information about a Council session when clicked.

Key Features:
- Shows individual model responses with rankings
- Displays evaluation scores breakdown
- Reveals which models produced which responses (de-anonymization)
- Shows evaluation reasoning (optional)
- Formats output in clean Markdown

Users can click this action button beneath any Council response to see
the full details of how the answer was synthesized.
"""

from pydantic import BaseModel, Field
from typing import Optional

# Import Council data structures
try:
    from schemas import extract_council_metadata, CouncilMode
except ImportError:
    import sys
    import os
    sys.path.insert(0, os.path.dirname(__file__))
    from schemas import extract_council_metadata, CouncilMode


class Action:
    """
    Show Details Action

    Interactive button that reveals Council session details
    """

    class Valves(BaseModel):
        """
        User-configurable options
        """
        SHOW_ANONYMOUS_IDS: bool = Field(
            default=True,
            description="Show anonymous response IDs in output"
        )

        SHOW_MODEL_IDENTITIES: bool = Field(
            default=True,
            description="Reveal which models produced which responses (de-anonymize)"
        )

        SHOW_EVALUATION_REASONING: bool = Field(
            default=False,
            description="Include evaluation reasoning in output"
        )

        SHOW_RESPONSE_CONTENT: bool = Field(
            default=True,
            description="Include full response content from each model"
        )

        SHOW_TIMING_INFO: bool = Field(
            default=True,
            description="Show timing and performance information"
        )

        ENABLE_DEBUG_LOGGING: bool = Field(
            default=False,
            description="Enable debug logging for this action"
        )

    def __init__(self):
        """Initialize the action"""
        self.valves = self.Valves()

    async def action(
        self,
        body: dict,
        __user__: Optional[dict] = None,
        __event_emitter__=None,
        __event_call__=None,
    ) -> dict:
        """
        Action execution: Display Council session details

        Args:
            body: Request body containing Council metadata
            __user__: User information
            __event_emitter__: Event emitter for status updates
            __event_call__: Event call for user interactions

        Returns:
            Dict with formatted details content
        """

        if self.valves.ENABLE_DEBUG_LOGGING:
            print("[Council Show Details] Action triggered")

        # Send status update
        if __event_emitter__:
            await __event_emitter__({
                "type": "status",
                "data": {
                    "description": "Loading Council details...",
                    "done": False
                }
            })

        # Extract Council metadata
        metadata = extract_council_metadata(body)

        if not metadata:
            return {
                "content": "**No Council Data Available**\n\nThis message was not generated by the Council of LLMs, or the session data is missing."
            }

        if self.valves.ENABLE_DEBUG_LOGGING:
            print(f"[Council Show Details] Session: {metadata.session_id}")
            print(f"[Council Show Details] Mode: {metadata.mode}")
            print(f"[Council Show Details] Responses: {len(metadata.responses)}")

        # Build detailed output
        output = self._build_details_output(metadata)

        # Send completion status
        if __event_emitter__:
            await __event_emitter__({
                "type": "status",
                "data": {
                    "description": "Details loaded",
                    "done": True
                }
            })

        return {"content": output}

    def _build_details_output(self, metadata) -> str:
        """
        Build formatted details output

        Args:
            metadata: CouncilMetadata object

        Returns:
            Markdown-formatted string with details
        """
        output = "# Council of LLMs - Session Details\n\n"

        # Session info
        output += f"**Session ID**: `{metadata.session_id}`\n"
        output += f"**Status**: {metadata.mode.value}\n"
        output += f"**Models Queried**: {len(metadata.models_queried)}\n"

        if metadata.completed_at and self.valves.SHOW_TIMING_INFO:
            duration = (metadata.completed_at - metadata.started_at).total_seconds()
            output += f"**Duration**: {duration:.2f}s\n"

        output += "\n---\n\n"

        # Individual responses with scores
        output += "## Individual Model Responses\n\n"

        if not metadata.responses:
            output += "*No responses available*\n\n"
        else:
            # Sort by rank
            sorted_responses = sorted(
                metadata.responses,
                key=lambda r: metadata.aggregated_scores.get(r.anonymous_id, type('obj', (), {'rank': 999})).rank
                if metadata.aggregated_scores.get(r.anonymous_id) else 999
            )

            for response in sorted_responses:
                output += self._format_response_detail(response, metadata)

        # Evaluation summary
        if metadata.aggregated_scores:
            output += "\n---\n\n"
            output += "## Evaluation Scores Summary\n\n"
            output += self._format_evaluation_summary(metadata)

        # Configuration
        output += "\n---\n\n"
        output += "## Configuration\n\n"
        output += self._format_configuration(metadata)

        return output

    def _format_response_detail(self, response, metadata) -> str:
        """
        Format a single response with its details

        Args:
            response: ModelResponse object
            metadata: CouncilMetadata object

        Returns:
            Formatted string for this response
        """
        output = ""

        # Get aggregated scores
        agg_scores = metadata.aggregated_scores.get(response.anonymous_id)

        # Header with rank
        if agg_scores and agg_scores.rank:
            output += f"### Rank #{agg_scores.rank}"
        else:
            output += f"### Response"

        # Anonymous ID (if enabled)
        if self.valves.SHOW_ANONYMOUS_IDS:
            output += f" ({response.anonymous_id})"

        # Reveal model identity (if enabled)
        if self.valves.SHOW_MODEL_IDENTITIES:
            output += f" - **{response.model_id}**"

        output += "\n\n"

        # Scores
        if agg_scores and agg_scores.average_scores:
            avg = agg_scores.average_scores
            output += f"**Scores**: "
            output += f"Accuracy: {avg.accuracy:.1f}/10, "
            output += f"Clarity: {avg.clarity:.1f}/10, "
            output += f"Completeness: {avg.completeness:.1f}/10, "
            output += f"Relevance: {avg.relevance:.1f}/10\n\n"
            output += f"**Weighted Total**: {agg_scores.weighted_total:.2f}/10 "
            output += f"(from {agg_scores.evaluator_count} evaluators)\n\n"

        # Performance metrics
        if response.tokens_used or response.latency_ms:
            output += "**Performance**: "
            if response.tokens_used:
                output += f"{response.tokens_used} tokens"
            if response.latency_ms:
                if response.tokens_used:
                    output += ", "
                output += f"{response.latency_ms:.0f}ms latency"
            output += "\n\n"

        # Response content (if enabled)
        if self.valves.SHOW_RESPONSE_CONTENT and response.content:
            output += "**Response**:\n\n"
            output += f"> {response.content}\n\n"

        # Error info (if failed)
        if not response.success and response.error:
            output += f"**Error**: {response.error}\n\n"

        output += "---\n\n"

        return output

    def _format_evaluation_summary(self, metadata) -> str:
        """
        Format evaluation scores summary

        Args:
            metadata: CouncilMetadata object

        Returns:
            Formatted evaluation summary
        """
        output = ""

        # Sort by rank
        sorted_scores = sorted(
            metadata.aggregated_scores.items(),
            key=lambda x: x[1].rank if x[1].rank else 999
        )

        output += "| Rank | Response | Accuracy | Clarity | Completeness | Relevance | Total |\n"
        output += "|------|----------|----------|---------|--------------|-----------|-------|\n"

        for anonymous_id, agg in sorted_scores:
            if not agg.average_scores:
                continue

            avg = agg.average_scores

            # Get response for model ID
            response = next((r for r in metadata.responses if r.anonymous_id == anonymous_id), None)
            model_display = response.model_id if (response and self.valves.SHOW_MODEL_IDENTITIES) else anonymous_id

            output += f"| {agg.rank} | {model_display} | "
            output += f"{avg.accuracy:.1f} | {avg.clarity:.1f} | "
            output += f"{avg.completeness:.1f} | {avg.relevance:.1f} | "
            output += f"**{agg.weighted_total:.2f}** |\n"

        output += "\n"

        # Show weights
        output += "**Evaluation Weights**: "
        weights = metadata.criteria_weights
        output += f"Accuracy: {weights.get('accuracy', 0):.0%}, "
        output += f"Clarity: {weights.get('clarity', 0):.0%}, "
        output += f"Completeness: {weights.get('completeness', 0):.0%}, "
        output += f"Relevance: {weights.get('relevance', 0):.0%}\n\n"

        # Show reasoning (if enabled)
        if self.valves.SHOW_EVALUATION_REASONING and metadata.evaluations:
            output += "\n### Evaluation Reasoning\n\n"
            # Show a sample of reasoning from evaluations
            for i, evaluation in enumerate(metadata.evaluations[:5]):  # Limit to 5
                if evaluation.reasoning:
                    output += f"- **{evaluation.evaluator_model_id}** on **{evaluation.target_anonymous_id}**: "
                    output += f"{evaluation.reasoning}\n"

        return output

    def _format_configuration(self, metadata) -> str:
        """
        Format configuration information

        Args:
            metadata: CouncilMetadata object

        Returns:
            Formatted configuration
        """
        output = ""

        output += f"**Models Queried**: {', '.join(metadata.models_queried)}\n\n"

        if metadata.lead_model_id:
            output += f"**Lead Synthesizer**: {metadata.lead_model_id}\n\n"

        if metadata.synthesis_input:
            output += f"**Top Responses Used for Synthesis**: {len(metadata.synthesis_input.top_responses)}\n\n"

        return output


# Module metadata
__version__ = "0.1.0"
__author__ = "Council Pipeline Team"
__description__ = "Show Details action with customizable display options"
